sudo: required
services:
  - docker

before_install:
  - docker build -t valdemaras/docker-sandbox -f Dockerfile.dev .

script:
  - docker run valdemaras/docker-sandbox npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-sandbox"
  env: "DockerSandbox-env"
  bucket_name: "elasticbeanstalk-us-east-2-761720858730"
  bucket_path: "docker-sandbox"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"